"""empty message

Revision ID: 3f9dc81bf206
Revises: a790e1562f2c
Create Date: 2022-10-26 02:51:57.613248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f9dc81bf206'
down_revision = 'a790e1562f2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Groups',
    sa.Column('groupId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('groupName', sa.String(length=20), nullable=False),
    sa.Column('groupOwner', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['groupOwner'], ['User.id'], ),
    sa.PrimaryKeyConstraint('groupId')
    )
    op.create_table('GroupMembers',
    sa.Column('group', sa.Integer(), nullable=False),
    sa.Column('member', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group'], ['Groups.groupId'], ),
    sa.ForeignKeyConstraint(['member'], ['User.id'], ),
    sa.PrimaryKeyConstraint('member')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('GroupMembers')
    op.drop_table('Groups')
    # ### end Alembic commands ###
