"""empty message

Revision ID: d48aac9361c8
Revises: dde1635eee2a
Create Date: 2022-10-21 15:59:20.444907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd48aac9361c8'
down_revision = 'dde1635eee2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('userId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firstName', sa.String(length=50), nullable=False),
    sa.Column('lastName', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=62), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('userId'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('userId', sa.INTEGER(), nullable=False),
    sa.Column('firstName', sa.VARCHAR(length=50), nullable=False),
    sa.Column('lastName', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=62), nullable=False),
    sa.Column('nickname', sa.VARCHAR(length=50), nullable=True),
    sa.Column('password', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('userId'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('User')
    # ### end Alembic commands ###
