"""empty message

Revision ID: 160d5e847a59
Revises: 3f9dc81bf206
Create Date: 2022-11-01 22:57:13.017600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '160d5e847a59'
down_revision = '3f9dc81bf206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Posts',
    sa.Column('postId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('postDateTime', sa.String(length=255), nullable=False),
    sa.Column('poster', sa.Integer(), nullable=True),
    sa.Column('groupAssociation', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(length=4096), nullable=False),
    sa.Column('postTags', sa.String(length=255), nullable=True),
    sa.Column('postImage', sa.String(length=255), nullable=True),
    sa.Column('postLikes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poster'], ['User.id'], ),
    sa.PrimaryKeyConstraint('postId')
    )
    op.create_table('PostLikes',
    sa.Column('postId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['postId'], ['Posts.postId'], ),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('postId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PostLikes')
    op.drop_table('Posts')
    # ### end Alembic commands ###
