"""refactored models into own file, added security questions table

Revision ID: 229dc369cd45
Revises: d48aac9361c8
Create Date: 2022-10-21 16:22:04.428729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '229dc369cd45'
down_revision = 'd48aac9361c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('userId', sa.INTEGER(), nullable=False),
    sa.Column('firstName', sa.VARCHAR(length=50), nullable=False),
    sa.Column('lastName', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=62), nullable=False),
    sa.Column('nickname', sa.VARCHAR(length=50), nullable=True),
    sa.Column('password', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('userId'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('User')
    # ### end Alembic commands ###
