"""empty message

Revision ID: 526aa35697b4
Revises: ef29e0a29338
Create Date: 2022-11-13 17:35:28.925940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526aa35697b4'
down_revision = 'ef29e0a29338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Profile',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('AboutMe', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('userId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Profile')
    # ### end Alembic commands ###
