"""empty message

Revision ID: a790e1562f2c
Revises: 229dc369cd45
Create Date: 2022-10-21 19:59:15.532477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a790e1562f2c'
down_revision = '229dc369cd45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firstName', sa.String(length=50), nullable=False),
    sa.Column('lastName', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=62), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('SecurityQuestions',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('Question1', sa.String(length=20), nullable=False),
    sa.Column('Answer1', sa.String(length=255), nullable=False),
    sa.Column('Question2', sa.String(length=20), nullable=False),
    sa.Column('Answer2', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('userId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SecurityQuestions')
    op.drop_table('User')
    # ### end Alembic commands ###
