"""empty message

Revision ID: ef29e0a29338
Revises: 
Create Date: 2022-10-30 18:00:46.261348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef29e0a29338'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firstName', sa.String(length=50), nullable=False),
    sa.Column('lastName', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=62), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Groups',
    sa.Column('groupId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('groupName', sa.String(length=20), nullable=False),
    sa.Column('groupOwner', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['groupOwner'], ['User.id'], ),
    sa.PrimaryKeyConstraint('groupId')
    )
    op.create_table('SecurityQuestions',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('Question1', sa.String(length=20), nullable=False),
    sa.Column('Answer1', sa.String(length=255), nullable=False),
    sa.Column('Question2', sa.String(length=20), nullable=False),
    sa.Column('Answer2', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_table('GroupMembers',
    sa.Column('group', sa.Integer(), nullable=False),
    sa.Column('member', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group'], ['Groups.groupId'], ),
    sa.ForeignKeyConstraint(['member'], ['User.id'], ),
    sa.PrimaryKeyConstraint('member')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('GroupMembers')
    op.drop_table('SecurityQuestions')
    op.drop_table('Groups')
    op.drop_table('User')
    # ### end Alembic commands ###
